# -*- coding: utf-8 -*-
"""final.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X61ww6oQQOUgH8-EV0iclTofDnm2qhh7
"""

N, P = map(int, input().split())
L = N * N

j= -1
k = 0
i = 0
P_fixo = P

if P > L:
    print(f"O astronauta ja saiu em missao ha {P-L} chamadas.")

else:
  while (P>0):
    aux = 0
    maximo = N-2*i
    while((aux<maximo) and P>0):
      j+=1
      P-=1
      aux += 1
    aux = 0
    while((aux<maximo-1) and P>0):
      k+=1
      P-=1
      aux +=1
    aux = 0
    while((aux<maximo-1) and P>0):
      j-=1
      P-=1
      aux +=1
    aux = 0
    while((aux<maximo-2) and P>0):
      k-=1
      P-=1
      aux +=1
    i +=1
  if (P_fixo) == L:
    print(f"O astronauta esta na posicao: {k} {j}\nPreste atencao, astronauta, chegou a sua vez!")
  else:
    print(f"O astronauta esta na posicao: {k} {j}\nAinda faltam {L-(P_fixo)} chamadas para a sua vez!")