# -*- coding: utf-8 -*-
"""exercicioLAB.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZQcLOmgwJtPLwRDzGzJx52LmX1nGa-na
"""

def remover_tag(linhas):
    dentro = False
    result = ''
    for char in linhas:
        if char == '<':
            dentro = True
        elif char == '>':
            dentro = False
        else:
            if not dentro:
                result += char
    return result

def processar_arq(arq_um, arq_output):
    with open(arq_um, 'r') as input1_f, open(arq_output, 'w') as output_f:
        for linhas in input1_f:
            text = remover_tag(linhas)
            text = text.strip()
            if text:
                print(text)
                output_f.write(text + '\n')

if __name__ == "__main__":
  archive = input().strip()
  arq = open(archive, "rt")
processar_arq(archive, "out.txt")