# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11yvZQx29EftEDILOqyHL_cpRqlf-SLs0
"""

import codecs
x = int(input())
teste = format(x, "x")
y = bytes.fromhex(teste)
z = codecs.decode(y, errors = "replace")
print(z)