# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pZL9isOOTlk9ePpcG14ReJHGGYPp72L5
"""

x = list(map(int, input().split())) #função map() irá aplicar o int() em cada elemento da lista
y = list(map(int, input().split()))

w1 = x[0] + x[2]
h1 = x[1] + x[3]
w2 = y[0] + y[2]
h2 = y[1] + y[3]

if (x[0]<=y[0]<=w1 or x[0]<=w2<=w1 or y[0]<=x[0]<=w2 or y[0]<=w1<= w2) and (x[1]<=y[1]<=h1 or x[1]<=h2<=h1 or y[1]<=x[1]<=h2 or y[1]<=h1<= h2):
        inter_x = max(x[0], y[0])
        inter_y = max(x[1], y[1])
        inter_w = max(0, min(w1, w2) - inter_x)
        inter_h = max(0, min(h1, h2) - inter_y)
        print("HIT:", inter_x, inter_y, inter_w, inter_h)
else:
        print("MISS")